@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Диаграмма системного контекста для компании "Теплый дом"

Person(customer, "Клиент 'Теплого Дома'", "Клиент который подключен к системе Теплого дома")
System(webapp, "Приложение 'Теплый дом'", "Позволяет пользователям получать данные датчиков и управлять ими")

System_Ext(api, "Система контроля датчиков", "Общается с датчиками посредством контрактов")
System_Ext(sensors, "Датчики", "Физические датчики установленные в доме")


Rel(customer, webapp, "Использует UI для просмотра и настроек датчиков")
Rel(webapp, api, "Отправляет запросы на получение данных")
Rel(sensors, api, "Отправляет сообщения на датчики для получение актуальных данных")
Rel(api, webapp, "Отдает текущий результат с датчиков")

@enduml